In [39]:
from pathlib import Path
import pandas as pd

pd.set_option('display.max_rows', 15)

file = Path(r"C:\Users\Administrator\Desktop\pandas进阶修炼")

df = pd.read_csv(file.joinpath('TOP250.txt'), encoding='gbk', sep='\t')

## 数据查看
### 1 - 查看数据维度
df.shape
# (250, 11)

### 2- 随机查看5条数据
df.sample(5)

### 3- 查看数据前后五行
df.head(5)
# df.tail(5)

### 4- 查看数据的基本信息
# df.info()

### 5- 查看数据统计信息 | 数值
df.describe()

### 6- 查看数据统计信息 | 离散  查看 离散型 列的统计信息，计数、频率什么
df.describe(include=['O'])

### 7- 查看数据统计信息｜整体
df.describe(include='all')

,片名,上映年份,评分,评价人数,导演,编剧,主演,类型,国家/地区,语言,时长(分钟)
count,250,250.000000,250.000000,2.500000e+02,250,250,250,250,250,250,250.000000
unique,249,NaN,NaN,NaN,180,221,249,120,20,26,NaN
top,小森林,NaN,NaN,NaN,宫崎骏,宫崎骏,桥本爱 / 三浦贵大 / 松冈茉优 / 温水洋一 / 桐岛加恋,剧情,美国,英语,NaN
freq,2,NaN,NaN,NaN,8,6,2,19,112,75,NaN
mean,NaN,2000.512000,8.903200,5.857653e+05,NaN,NaN,NaN,NaN,NaN,NaN,122.664000
std,NaN,15.831247,0.262192,3.700662e+05,NaN,NaN,NaN,NaN,NaN,NaN,29.339843
min,NaN,1931.000000,8.400000,1.064620e+05,NaN,NaN,NaN,NaN,NaN,NaN,45.000000
25%,NaN,1995.000000,8.700000,3.398110e+05,NaN,NaN,NaN,NaN,NaN,NaN,102.000000
50%,NaN,2004.000000,8.900000,4.841685e+05,NaN,NaN,NaN,NaN,NaN,NaN,118.000000
75%,NaN,2011.000000,9.100000,7.031858e+05,NaN,NaN,NaN,NaN,NaN,NaN,136.000000
max,NaN,2019.000000,9.700000,2.317937e+06,NaN,NaN,NaN,NaN,NaN,NaN,238.000000

In [67]:
## 缺失值处理
### 8- 计算缺失值 总计
df = pd.read_csv(file.joinpath('TOP250.txt'), encoding='gbk', sep='\t')
df.isna().sum().sum()

### 9 - 计算缺失值｜分列
df.isnull().sum()

### 10 - 查看缺失值
df[df.isna()]

### 10 - 查看缺失值 为了后面更方便的处理缺失值，现在先看看全部缺失值所在的行
df.loc[df.isna().T.any(), :]

### 11- 高亮缺失值
(
    df.style
    .highlight_null(props="background-color:blue;color:yellow")
)

### 12- 删除缺失值
df.dropna(how='any')

### 13- 缺失值不全 | 整体填充
df.fillna('*')

### 14 - 缺失值补全｜向上填充
df.fillna(method='pad')

### 15 - 缺失值补全｜整体均值填充
df.评价人数.fillna(df.评价人数.mean())

### 16 - 缺失值补全｜上下均值填充 除了可以使用整列的均值进行填充，也可以使用缺失值位置的上下均值进行填充、

df.评价人数.fillna(df.评价人数.interpolate())

### 17 -缺失值补全｜匹配填充 除了利用均值填充，有时还需要根据另一列的值进行匹配填充

# -> 现在填充 “语言” 列的缺失值，要求根据 “国家/地区” 列的值进行填充

# 例如 《海上钢琴师》国家/地区为 意大利，根据其他意大利国家对应的语言来看，应填充为 意大利语

df.groupby('国家/地区').语言.bfill()

### 18 - 查找重复值 将全部重复值所在的行筛选出来
df[df.duplicated()]

### 19 -查找重复值｜指定 上面是所有列完全重复的情况，但有时我们只需要根据某列查找重复值
df[df.duplicated(['片名'])]

### 20 - 删除重复值
df = df.drop_duplicates()

### 21 - 删除重复值｜指定
df.drop_duplicates(keep='last')

Empty DataFrame
Columns: [片名, 上映年份, 评分, 评价人数, 导演, 编剧, 主演, 类型, 国家/地区, 语言, 时长(分钟)]
Index: []